// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: const.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from const.proto</summary>
  public static partial class ConstReflection {

    #region Descriptor
    /// <summary>File descriptor for const.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConstReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgtjb25zdC5wcm90bxIFUHJvdG8qgQMKCUVycm9yQ29kZRIJCgVFcnJvchAA",
            "EgYKAk9LEAESEAoMTG9naW5GYWlsdXJlEAISFAoQUmVnRXhpc3RVc2VyTmFt",
            "ZRADEhcKE1JlZ0lucHV0RW1wdHlPck51bGwQBBIUChBOb0dhbWVQbGF5ZXJE",
            "YXRhEAUSDgoKTm9IZXJvSW5mbxAGEhMKD05PRm91bmRTZXJ2ZXJJRBAHEhYK",
            "Ek5PRnJlZUJhdHRsZVNlcnZlchAIEhQKEFBsYXllcklzSW5CYXR0bGUQCRId",
            "ChlCYXR0bGVTZXJ2ZXJIYXNEaXNjb25uZWN0EAoSHQoZTk9Gb3VuZFVzZXJP",
            "bkJhdHRsZVNlcnZlchALEhsKF05PRm91bmRVc2VyQmF0dGxlU2VydmVyEAwS",
            "DwoLTk9Gb3VuZEl0ZW0QDRIQCgxOT0Vub3VnaEl0ZW0QDhIQCgxJc1dlYXJP",
            "bkhlcm8QDxIRCg1Ob0Vub3VnaHRHb2xkEBASFAoQTm9GcmVlR2F0ZVNlcnZl",
            "chARYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.ErrorCode), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///错误码 考虑平台问题 不要尝试串码
  /// </summary>
  public enum ErrorCode {
    /// <summary>
    ///VersionError=9999;//协议版本异常
    /// </summary>
    [pbr::OriginalName("Error")] Error = 0,
    /// <summary>
    ///处理成功
    /// </summary>
    [pbr::OriginalName("OK")] Ok = 1,
    /// <summary>
    ///登陆失败
    /// </summary>
    [pbr::OriginalName("LoginFailure")] LoginFailure = 2,
    /// <summary>
    ///用户名重复
    /// </summary>
    [pbr::OriginalName("RegExistUserName")] RegExistUserName = 3,
    /// <summary>
    ///输入为空
    /// </summary>
    [pbr::OriginalName("RegInputEmptyOrNull")] RegInputEmptyOrNull = 4,
    /// <summary>
    ///没有游戏角色信息
    /// </summary>
    [pbr::OriginalName("NoGamePlayerData")] NoGamePlayerData = 5,
    /// <summary>
    ///英雄数据异常
    /// </summary>
    [pbr::OriginalName("NoHeroInfo")] NoHeroInfo = 6,
    /// <summary>
    ///没有对应的serverID
    /// </summary>
    [pbr::OriginalName("NOFoundServerID")] NofoundServerId = 7,
    /// <summary>
    ///没有空闲的战斗服务器
    /// </summary>
    [pbr::OriginalName("NOFreeBattleServer")] NofreeBattleServer = 8,
    /// <summary>
    ///玩家已经在战斗中
    /// </summary>
    [pbr::OriginalName("PlayerIsInBattle")] PlayerIsInBattle = 9,
    /// <summary>
    ///战斗服务器已经断开连接
    /// </summary>
    [pbr::OriginalName("BattleServerHasDisconnect")] BattleServerHasDisconnect = 10,
    /// <summary>
    ///没有申请战斗服务器
    /// </summary>
    [pbr::OriginalName("NOFoundUserOnBattleServer")] NofoundUserOnBattleServer = 11,
    /// <summary>
    ///没有战斗服务器
    /// </summary>
    [pbr::OriginalName("NOFoundUserBattleServer")] NofoundUserBattleServer = 12,
    /// <summary>
    ///没有道具
    /// </summary>
    [pbr::OriginalName("NOFoundItem")] NofoundItem = 13,
    /// <summary>
    ///道具数量不足
    /// </summary>
    [pbr::OriginalName("NOEnoughItem")] NoenoughItem = 14,
    /// <summary>
    ///穿戴中
    /// </summary>
    [pbr::OriginalName("IsWearOnHero")] IsWearOnHero = 15,
    /// <summary>
    ///金币不足
    /// </summary>
    [pbr::OriginalName("NoEnoughtGold")] NoEnoughtGold = 16,
    /// <summary>
    ///没有空闲网关服务器
    /// </summary>
    [pbr::OriginalName("NoFreeGateServer")] NoFreeGateServer = 17,
  }

  #endregion

}

#endregion Designer generated code
