// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: excelconst.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from excelconst.proto</summary>
  public static partial class ExcelconstReflection {

    #region Descriptor
    /// <summary>File descriptor for excelconst.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExcelconstReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBleGNlbGNvbnN0LnByb3RvEgVQcm90byoyCgtEZWZhbmNlVHlwZRIKCgZO",
            "b3JtYWwQABIKCgZTaGllbGQQARILCgdBcm1vcmVkEAIqPgoMSGVyb0NhdGVn",
            "b3J5EgwKCEhDX0ZvcmNlEAASEAoMSENfS25vd2xlZGdlEAESDgoKSENfQWdp",
            "bGl0eRACKjQKCkRhbWFnZVR5cGUSDQoJQ29uZnVzaW9uEAASDAoIUGh5c2lj",
            "YWwQARIJCgVNYWdpYxACKlEKD0xldmVsVW5sb2NrVHlwZRIICgROb25lEAAS",
            "FQoRTmVlZENvbXBsZXRlTGV2ZWwQARIMCghOZWVkSXRlbRACEg8KC0NvbnN1",
            "bWVJdGVtEAMq7QEKEEhlcm9Qcm9wZXJ0eVR5cGUSDAoISFBUX05vbmUQABIL",
            "CgdEZWZhbmNlEAESDQoJRGFtYWdlTWluEAISDQoJRGFtYWdlTWF4EAMSCQoF",
            "TWF4SFAQBBIJCgVNYXhNUBAFEgkKBUZvcmNlEAYSDQoJS25vd2xlZGdlEAcS",
            "CwoHQWdpbGl0eRAIEggKBEpvdWsQCRIHCgNDcnQQChIHCgNIaXQQCxIRCg1S",
            "ZXNpc3RpYmlsaXR5EAwSEQoNTWFnaWNXYWl0VGltZRANEg8KC1N1Y2tpbmdS",
            "YXRlEA4SEAoMVmlld0Rpc3RhbmNlEA8qVQoOQWN0aW9uTG9ja1R5cGUSDAoI",
            "QUxUX05vbmUQABIMCghOT19TS0lMTBABEgsKB05PX01PVkUQAhINCglOT19B",
            "VFRBQ0sQBBILCgdJTkhJREVOEAgqRgoISXRlbVR5cGUSCwoHSVRfTm9uZRAA",
            "Eg8KC0lUX1VzZU1hZ2ljEAESDgoKSVRfQ29uc3VtZRACEgwKCElUX0VxdWlw",
            "EAMqSgoQTWFnaWNSZWxlYXNlVHlwZRIUChBNUlRfTm9ybWFsQXR0YWNrEAAS",
            "DQoJTVJUX01hZ2ljEAESEQoNTVJUX0Jvcm5NYWdpYxACKkIKFE1hZ2ljUmVs",
            "ZWFzZUFJVGFyZ2V0Eg8KC0VuZW15VGFyZ2V0EAASDgoKVGVhbVRhcmdldBAB",
            "EgkKBU93bmVyEAIqNgoNRXF1aXBtZW50VHlwZRIICgRIZWFkEAASBwoDQXJt",
            "EAESCAoEQm9keRACEggKBEZvb3QQAyqPAQoMR2V0VmFsdWVGcm9tEhEKDUN1",
            "cnJlbnRDb25maWcQABIUChBNYWdpY0xldmVsUGFyYW0xEAESFAoQTWFnaWNM",
            "ZXZlbFBhcmFtMhACEhQKEE1hZ2ljTGV2ZWxQYXJhbTMQAxIUChBNYWdpY0xl",
            "dmVsUGFyYW00EAQSFAoQTWFnaWNMZXZlbFBhcmFtNRAFKlIKDlRhcmdldFRl",
            "YW1UeXBlEgcKA0FMTBAAEgkKBUVuZW15EAESCwoHT3duVGVhbRACEhYKEk93",
            "blRlYW1XaXRoT3V0U2VsZhADEgcKA093bhAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.DefanceType), typeof(global::Proto.HeroCategory), typeof(global::Proto.DamageType), typeof(global::Proto.LevelUnlockType), typeof(global::Proto.HeroPropertyType), typeof(global::Proto.ActionLockType), typeof(global::Proto.ItemType), typeof(global::Proto.MagicReleaseType), typeof(global::Proto.MagicReleaseAITarget), typeof(global::Proto.EquipmentType), typeof(global::Proto.GetValueFrom), typeof(global::Proto.TargetTeamType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///防御类型
  /// </summary>
  public enum DefanceType {
    /// <summary>
    ///普通
    /// </summary>
    [pbr::OriginalName("Normal")] Normal = 0,
    /// <summary>
    ///盾牌
    /// </summary>
    [pbr::OriginalName("Shield")] Shield = 1,
    /// <summary>
    ///重甲
    /// </summary>
    [pbr::OriginalName("Armored")] Armored = 2,
  }

  /// <summary>
  ///种族类型
  /// </summary>
  public enum HeroCategory {
    /// <summary>
    ///力量
    /// </summary>
    [pbr::OriginalName("HC_Force")] HcForce = 0,
    /// <summary>
    ///智力
    /// </summary>
    [pbr::OriginalName("HC_Knowledge")] HcKnowledge = 1,
    /// <summary>
    ///敏捷
    /// </summary>
    [pbr::OriginalName("HC_Agility")] HcAgility = 2,
  }

  /// <summary>
  ///伤害类型
  /// </summary>
  public enum DamageType {
    /// <summary>
    ///混乱
    /// </summary>
    [pbr::OriginalName("Confusion")] Confusion = 0,
    /// <summary>
    ///物理
    /// </summary>
    [pbr::OriginalName("Physical")] Physical = 1,
    /// <summary>
    ///魔法
    /// </summary>
    [pbr::OriginalName("Magic")] Magic = 2,
  }

  /// <summary>
  ///解锁条件
  /// </summary>
  public enum LevelUnlockType {
    /// <summary>
    ///无需解锁
    /// </summary>
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    ///前置关卡
    /// </summary>
    [pbr::OriginalName("NeedCompleteLevel")] NeedCompleteLevel = 1,
    /// <summary>
    ///需求道具
    /// </summary>
    [pbr::OriginalName("NeedItem")] NeedItem = 2,
    /// <summary>
    ///消耗道具
    /// </summary>
    [pbr::OriginalName("ConsumeItem")] ConsumeItem = 3,
  }

  /// <summary>
  ///属性枚举
  /// </summary>
  public enum HeroPropertyType {
    [pbr::OriginalName("HPT_None")] HptNone = 0,
    /// <summary>
    ///防御
    /// </summary>
    [pbr::OriginalName("Defance")] Defance = 1,
    /// <summary>
    ///伤害
    /// </summary>
    [pbr::OriginalName("DamageMin")] DamageMin = 2,
    /// <summary>
    ///伤害大
    /// </summary>
    [pbr::OriginalName("DamageMax")] DamageMax = 3,
    /// <summary>
    ///HP
    /// </summary>
    [pbr::OriginalName("MaxHP")] MaxHp = 4,
    /// <summary>
    ///魔法上限
    /// </summary>
    [pbr::OriginalName("MaxMP")] MaxMp = 5,
    /// <summary>
    ///力量
    /// </summary>
    [pbr::OriginalName("Force")] Force = 6,
    /// <summary>
    ///智慧
    /// </summary>
    [pbr::OriginalName("Knowledge")] Knowledge = 7,
    /// <summary>
    ///敏捷
    /// </summary>
    [pbr::OriginalName("Agility")] Agility = 8,
    /// <summary>
    ///闪避
    /// </summary>
    [pbr::OriginalName("Jouk")] Jouk = 9,
    /// <summary>
    ///暴击
    /// </summary>
    [pbr::OriginalName("Crt")] Crt = 10,
    /// <summary>
    ///命中
    /// </summary>
    [pbr::OriginalName("Hit")] Hit = 11,
    /// <summary>
    ///魔法躲避
    /// </summary>
    [pbr::OriginalName("Resistibility")] Resistibility = 12,
    /// <summary>
    ///普通攻击间隔时间
    /// </summary>
    [pbr::OriginalName("MagicWaitTime")] MagicWaitTime = 13,
    /// <summary>
    ///吸血等级
    /// </summary>
    [pbr::OriginalName("SuckingRate")] SuckingRate = 14,
    /// <summary>
    ///视野范围
    /// </summary>
    [pbr::OriginalName("ViewDistance")] ViewDistance = 15,
  }

  /// <summary>
  ///行为锁
  /// </summary>
  public enum ActionLockType {
    [pbr::OriginalName("ALT_None")] AltNone = 0,
    /// <summary>
    ///禁止释放主动技能
    /// </summary>
    [pbr::OriginalName("NO_SKILL")] NoSkill = 1,
    /// <summary>
    ///禁止移动
    /// </summary>
    [pbr::OriginalName("NO_MOVE")] NoMove = 2,
    /// <summary>
    ///禁止攻击
    /// </summary>
    [pbr::OriginalName("NO_ATTACK")] NoAttack = 4,
    /// <summary>
    ///隐形
    /// </summary>
    [pbr::OriginalName("INHIDEN")] Inhiden = 8,
  }

  public enum ItemType {
    [pbr::OriginalName("IT_None")] ItNone = 0,
    /// <summary>
    ///魔法道具   使用后调用参数1的魔法
    /// </summary>
    [pbr::OriginalName("IT_UseMagic")] ItUseMagic = 1,
    /// <summary>
    ///消耗类道具 本身没有任何功能其他系统定义
    /// </summary>
    [pbr::OriginalName("IT_Consume")] ItConsume = 2,
    /// <summary>
    ///装备
    /// </summary>
    [pbr::OriginalName("IT_Equip")] ItEquip = 3,
  }

  public enum MagicReleaseType {
    /// <summary>
    ///普通攻击
    /// </summary>
    [pbr::OriginalName("MRT_NormalAttack")] MrtNormalAttack = 0,
    /// <summary>
    ///魔法
    /// </summary>
    [pbr::OriginalName("MRT_Magic")] MrtMagic = 1,
    /// <summary>
    ///出生技能
    /// </summary>
    [pbr::OriginalName("MRT_BornMagic")] MrtBornMagic = 2,
  }

  public enum MagicReleaseAITarget {
    /// <summary>
    ///敌方目标
    /// </summary>
    [pbr::OriginalName("EnemyTarget")] EnemyTarget = 0,
    /// <summary>
    ///己方目标
    /// </summary>
    [pbr::OriginalName("TeamTarget")] TeamTarget = 1,
    /// <summary>
    ///自己
    /// </summary>
    [pbr::OriginalName("Owner")] Owner = 2,
  }

  public enum EquipmentType {
    /// <summary>
    ///头
    /// </summary>
    [pbr::OriginalName("Head")] Head = 0,
    /// <summary>
    ///手
    /// </summary>
    [pbr::OriginalName("Arm")] Arm = 1,
    /// <summary>
    ///衣服护驾
    /// </summary>
    [pbr::OriginalName("Body")] Body = 2,
    /// <summary>
    ///脚
    /// </summary>
    [pbr::OriginalName("Foot")] Foot = 3,
  }

  public enum GetValueFrom {
    /// <summary>
    ///获取当前配置值
    /// </summary>
    [pbr::OriginalName("CurrentConfig")] CurrentConfig = 0,
    /// <summary>
    ///取魔法等级表数据参数1
    /// </summary>
    [pbr::OriginalName("MagicLevelParam1")] MagicLevelParam1 = 1,
    [pbr::OriginalName("MagicLevelParam2")] MagicLevelParam2 = 2,
    [pbr::OriginalName("MagicLevelParam3")] MagicLevelParam3 = 3,
    [pbr::OriginalName("MagicLevelParam4")] MagicLevelParam4 = 4,
    [pbr::OriginalName("MagicLevelParam5")] MagicLevelParam5 = 5,
  }

  public enum TargetTeamType {
    /// <summary>
    ///所有
    /// </summary>
    [pbr::OriginalName("ALL")] All = 0,
    /// <summary>
    ///敌人
    /// </summary>
    [pbr::OriginalName("Enemy")] Enemy = 1,
    /// <summary>
    ///自己队友
    /// </summary>
    [pbr::OriginalName("OwnTeam")] OwnTeam = 2,
    /// <summary>
    ///不包含自己
    /// </summary>
    [pbr::OriginalName("OwnTeamWithOutSelf")] OwnTeamWithOutSelf = 3,
    /// <summary>
    ///只有自己
    /// </summary>
    [pbr::OriginalName("Own")] Own = 4,
  }

  #endregion

}

#endregion Designer generated code
